tenants:
  db-sources:
    HRMS1:
      jdbcUrl : jdbc:postgresql://hrms-1.cga0ulpkae0p.ap-south-1.rds.amazonaws.com:5432/hrms
      driverClassName : org.postgresql.Driver
      username : postgres
      password : hrmsportal2024
      schema : hrms_1
    HRMS2:
      jdbcUrl : jdbc:postgresql://hrms-1.cga0ulpkae0p.ap-south-1.rds.amazonaws.com:5432/hrms
      driverClassName : org.postgresql.Driver
      username : postgres
      password : hrmsportal2024
      schema : hrms_2
    MASTER:
       jdbcUrl : jdbc:postgresql://hrms-1.cga0ulpkae0p.ap-south-1.rds.amazonaws.com:5432/hrms
       driverClassName : org.postgresql.Driver
       username : postgres
       password : hrmsportal2024
       schema : hrms_mst    